import 'bootstrap/dist/css/bootstrap.min.css';
import Script from "next/script";
import Providers from "../components/Provider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <head>
            <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
        </head>
      <body>
      <Providers>
          {children}
      </Providers>
      </body>
    </html>
  )
}
